### ISSUE TITLE
tetrateFIPS NIST certificate details?

### ISSUE THREAD

**Issue by howels** [tetratelabs/getmesh#106]
We are evaluating FIPS support and whilst I can see claims of FIPS compliance (https://www.tetrate.io/blog/tetrate-istio-distro-achieves-fips-certification/) the FIPS certificate details are not available, which calls into question the validity of the FIPS compliance.
Please can we see the FIPS certificate to determine if tetrateFIPS is in fact FIPS 140-2 compliant?

Thanks

**Comment by pmerrison** [comment]
Hi @howels - please reach out to our sales team using [this form](https://www.tetrate.io/contact-us-sales/), they'll be able to help you
