### ISSUE TITLE
getmesh version: reports open source istio version under TID

### ISSUE THREAD

**Issue by pydevops** [tetratelabs/getmesh#117]
### What happened?

control plane version shows open source istio version vs others reports other tetratefips version. 

```
$ getmesh version
getmesh version: 1.1.4
active istioctl: 1.16.0-tetratefips-v0
client version: 1.16.0-tetratefips-v0
control plane version: 1.16.0
data plane version: 1.16.0-tetratefips-v0 (9 proxies)
```

### What did you expect to happen?

control plane shows the tetratefips version as well as the container images in istio-system are shown as below.

```
[containers.istio.tetratelabs.com/pilot:1.16.0-tetratefips-v0](http://containers.istio.tetratelabs.com/pilot:1.16.0-tetratefips-v0)
[containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0](http://containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0)
[containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0](http://containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0)
[containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0](http://containers.istio.tetratelabs.com/proxyv2:1.16.0-tetratefips-v0)
```

### TID istio version

only tested the following two versions: 
- 1.15.3
- 1.16.0

### Cloud provider
AWS

### Installation method

Use IstioOperator with istioctl. 

```
HUB=containers.istio.tetratelabs.com
DISTRO=1.16.0-tetratefips-v0
getmesh istioctl manifest install -f dev.yaml --set hub=${HUB} --set tag=${DISTRO}
```

**Comment by psbrar99** [comment]
@pydevops :Thanks for raising the issue, we are looking into this.

**Comment by psbrar99** [comment]
It's  the expected behaviour. 
getmesh will report versions reported by istioctl. If you run the istioctl version command in the same env it will report the same versions like this. The controlplane version is fetched from xds api and reports build version and not based on tags. As long as you have correct image in istiod deployment, it should be fine.

```
$ istioctl version
client version: 1.16.0-tetratefips-v0
control plane version: 1.16.0
data plane version: 1.16.0-tetratefips-v0 (9 proxies)
```

**Comment by pydevops** [comment]
@psbrar99 cool, thanks for clarification. I will close the issue now.
