### ISSUE TITLE
Is it intend to remove the support of 1.16.2 ?

### ISSUE THREAD

**Issue by MobsMao** [tetratelabs/getmesh#131]
From PR https://github.com/tetratelabs/getmesh/pull/130
You simply change the 1.16.2 version to 1.16.3. Which means that 1.16.2 is took down from your support list, Can you confirm it is intended or just a mistake?

![image](https://user-images.githubusercontent.com/9639541/223356923-7c481ef7-1d9e-4daf-b8a0-4b800325f08c.png)

**Comment by Marc-Morata-Fite** [comment]
Thank you @MobsMao. We have addressed this problem here: https://github.com/tetratelabs/getmesh/pull/132

Thanks for your contribution.
