### ISSUE TITLE
`install.sh` does not add GETMESH_HOME to the path

### ISSUE THREAD

**Issue by toffentoffen** [tetratelabs/getmesh#63]
I've tried to install getmesh cli by executing `curl -sL https://istio.tetratelabs.io/getmesh/install.sh | bash`.
The output is the following:
```
bash-3.2$ curl -sL https://istio.tetratelabs.io/getmesh/install.sh | bash
tetratelabs/getmesh info checking GitHub for latest tag
tetratelabs/getmesh info found version: 1.1.2 for v1.1.2/darwin/arm64
tetratelabs/getmesh info installed /Users/marcnavarro/.getmesh/bin/getmesh
```
No errors, but also no [successful installation message](https://github.com/tetratelabs/getmesh/blob/fd6d94abb71d3eaefc0724558e0636e7f5229b9f/site/install.sh#L476).

My first though was that the [command to grep GETMESH_HOME](https://github.com/tetratelabs/getmesh/blob/fd6d94abb71d3eaefc0724558e0636e7f5229b9f/site/install.sh#L471) from the detected profile was failing somehow, so I added an `else` statement:
```
    log_info "profile detected at ($detected_profile)"
    if ! command grep -qc 'GETMESH_HOME' "$detected_profile"; then
      log_info "updating user profile ($detected_profile)..."
      log_info "the following two lines are added into your profile ($detected_profile):" 
      printf "\n$path_str\n"
      command printf "$path_str" >> "$detected_profile"
      printf "\nFinished installation. Open a new terminal to start using getmesh!\n"
    else
      log_info "your profile already contains GETMESH_HOME in the path" #expected log_info
    fi
```

But surprisingly, the expected log_info (added in the else part) was no being printed. And my profile still doesn't contain any GETMESH_HOME.
```
bash-3.2$ ./install.sh
tetratelabs/getmesh info checking GitHub for latest tag
tetratelabs/getmesh info found version: 1.1.2 for v1.1.2/darwin/arm64
tetratelabs/getmesh info installed /Users/marcnavarro/.getmesh/bin/getmesh
tetratelabs/getmesh info profile detected at (/Users/marcnavarro/.zshrc)
```
I've been playing around trying to figure out what was the culprit, but couldn't really figure it out. Don't know if `command`, or my OS, or my ARCH (Apple m1), or zsh default version from mac osx bigsur. 
Moreover `command grep ...`  seems to execute correctly if the `-q` one can see the output of `0`.

The only solution that I found was storing `grep's` count output into a variable and compare the output to 0:
```
    log_info "profile detected at ($detected_profile)"
    
    local getmesh_in_profile=$(command grep -c 'GETMESH_HOME' "$detected_profile")
    
    log_info "found ($getmesh_in_profile) GETMESH_HOME in detected profile"
 
    if [[ "$getmesh_in_profile" -eq 0 ]]; then
      log_info "updating user profile ($detected_profile)..."
      log_info "the following two lines are added into your profile ($detected_profile):" 
      printf "\n$path_str\n"
      command printf "$path_str" >> "$detected_profile"
      printf "\nFinished installation. Open a new terminal to start using getmesh!\n"
    else
      log_info "your profile already contains getmesh in the path"
    fi
```

Now it worked:
```
marcnavarro@Marcs-MacBook-Pro ~ % ./install_debug.sh
tetratelabs/getmesh info checking GitHub for latest tag
tetratelabs/getmesh info found version: 1.1.2 for v1.1.2/darwin/arm64
tetratelabs/getmesh info installed /Users/marcnavarro/.getmesh/bin/getmesh
tetratelabs/getmesh info profile detected and found (/Users/marcnavarro/.zshrc)
tetratelabs/getmesh info found (0) GETMESH_HOME in detected profile
tetratelabs/getmesh info updating user profile (/Users/marcnavarro/.zshrc)...
tetratelabs/getmesh info the following two lines are added into your profile (/Users/marcnavarro/.zshrc):

export GETMESH_HOME="$HOME/.getmesh"
export PATH="$GETMESH_HOME/bin:$PATH"

Finished installation. Open a new terminal to start using getmesh!
```

Do you know what could be the problem of the actual code in main?
Should I create a PR with the proposed workaround of comparing `grep's` count result?

**Comment by toffentoffen** [comment]
I think I've found the reason why it is failing, and it's failing on macOSX BigSur bash (GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)). MacOsX Bigsur is shipped with a really old version.
It seems that enabling `errexit` https://github.com/tetratelabs/getmesh/blob/fd6d94abb71d3eaefc0724558e0636e7f5229b9f/site/install.sh#L16 
is making the script exit when `if  ! command grep -qc 'GETMESH_HOME' "$detected_profile"; then` is executed . Even though it is a tested command (inside an *if*). A tested command, as per gnu bash [documentation](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html), is:
> The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test in an if statement, part of any command executed in a && or || list except the command following the final && or ||

Extensive information about `set -e` can be found at http://mywiki.wooledge.org/BashFAQ/105
 which includes as well a reference to how subshells have propagated that flag https://www.in-ulm.de/~mascheck/various/set-e/

**Possible Solutions**
- Use `set +e` before the problematic `if` statement: I would discard that option because we will need to remember to set it back, and if the code branching changes over time it can be difficult to maintain it.
- Subshells. Seems like subshell does the trick because `set -e` is not propagated (maybe even by mistake). We can either:
  - extracting out the `grep` command and storing the count into a local variable:
  ```
    local getmesh_home_count=$(command grep -c 'GETMESH_HOME' "$detected_profile")
    if [[ "$getmesh_home_count" -eq 0 ]];
```
  - wrap the if command in parenthesis: `if  ! (command grep -qc 'GETMESH_HOME' "$detected_profile"); then`
- Remove `set -e` from the script as it seems problematic. I would suggest avoid that approach as it will make us to implement error handling manually at each command. Although it might be the best, I don't think it is worth the effort as this problem might only happen in concrete bash versions. 

I will go ahead and create a PR for using the wrap if statement approach.

**Comment by mathetake** [comment]
thanks so much @toffentoffen for the thorough investigation! 

> I will go ahead and create a PR for using the wrap if statement approach.

agreed, thank you! 😄
