### ISSUE TITLE
Wrong istio selection on FIPS enabled node

### ISSUE THREAD

**Issue by jackalsh** [tetratelabs/getmesh#69]
While fetching the last fips version using last getmesh client 
`getmesh fetch --version 1.10.3 --flavor tetratefips`
I get the following error

`
$ getmesh fetch --version 1.10.3 --flavor tetratefips
fallback to the flavor 0 version which is the latest one in 1.10.3-tetratefips
Downloading 1.10.3-tetratefips-v0 from https://istio.tetratelabs.io/getmesh/files/istio-1.10.3-tetratefips-v0-linux.tar.gz ...error while dowloading istio: exit status 22
`

From the logs I see, that it takes non existing file https://istio.tetratelabs.io/getmesh/files/istio-1.10.3-tetratefips-v0-linux.tar.gz. The correct on is with amd64 at the end.

Seems like the issue happens only when I run it on FIPS enabled runner.

Probably related to this PR: https://github.com/tetratelabs/getmesh/pull/66

**Comment by mathetake** [comment]
@jackalsh thanks for this, but i believe you are using an older getmesh cli.- please update to the latest one which resolved this bug, via `curl -sL https://istio.tetratelabs.io/getmesh/install.sh | bash` and try again. Feel free to reopen this if this issue persists with the latest one.
