### ISSUE TITLE
getmesh command line fails with -f error

### ISSUE THREAD

**Issue by batchamalick** [tetratelabs/getmesh#93]
While following the [doc](https://getistio.io/istio-in-practice/multiple-ingress-gateways/) the command is failing with the error 
```
getmesh istioctl install -f istio-2-gw.yaml                           
error executing istioctl: exit status 64, Error: unknown shorthand flag: 'f' in -f
````
I'm not sure if the same command worked for previous releases but not working anymore.
We need to update the step with the correct command or remove it completely

**Comment by incfly** [comment]
Thanks @psbrar99 . tried with master HEAD dev build `getmesh` seems working now.
